name: Pull Request Build and Deploy

on:
  pull_request:
    branches: [ dev ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: pr-dev
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: subosito/flutter-action@v1
      with:
          flutter-version: '2.8.0'
    - name: Getting dependencies
      run: |
        flutter pub get
    - name: Build
      run: flutter build web --target lib/main_development.dart
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: mi-libro-vecino-dev
        expires: 1h
